// [PrintTSROSEHeader]
/**
 * ENetUC_TransportROSE
 * "UC-Server-Access-Protocol-Transport" ASN.1 stubs.
 * This file was generated by estos esnacc (V6.0.19, 20.09.2024)
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
 */

// prettier-ignore
/* eslint-disable */
// [PrintTSROSEImports]
// Global imports
import { IENetUC_TransportROSE, IENetUC_TransportROSE_Handler } from "./ENetUC_TransportROSE_Interface";
import { ROSEError, ROSEInvoke, ROSEReject, ROSEResult } from "./SNACCROSE";
import { AsnInvokeProblem, AsnInvokeProblemEnum, createInvokeReject, IASN1Transport, IASN1LogData, IReceiveInvokeContext, IInvokeHandler, ELogSeverity, ROSEBase } from "./TSROSEBase";
import { ISendInvokeContextParams } from "./TSInvokeContext";
// Local imports
import * as ENetUC_Transport from "./ENetUC_Transport";
import * as Converter from "./ENetUC_Transport_Converter";
// [PrintTSImports]
import * as ENetUC_Common from "./ENetUC_Common";
import * as ENetUC_Auth from "./ENetUC_Auth";
import * as ENetUC_Common_Auth from "./ENetUC_Common_Auth";
import * as ENetUC_Common_Converter from "./ENetUC_Common_Converter";
import * as ENetUC_Auth_Converter from "./ENetUC_Auth_Converter";
import * as ENetUC_Common_Auth_Converter from "./ENetUC_Common_Auth_Converter";
// [PrintTSRootTypes]
export const MODULE_NAME = "ENetUC_TransportROSE";
export const MODULE_LASTCHANGE = "1970-01-01T00:00:00Z";
export const MODULE_MAJOR_VERSION = 8;
export const MODULE_MINOR_VERSION = 0;
export const MODULE_VERSION = "8.0.0";

// [PrintTSROSEOperationDefines]
export enum OperationIDs {
	OPID_asnStartTLS = 1103,
	OPID_asnTransportKeepAlive = 1706,
	OPID_asnTokenVerifyV2 = 1719,
	OPID_asnCheckConnection = 1714,
	OPID_asnCreateAuthToken = 1724
}

// [PrintTSROSEModuleComment]
/**
 * Transport layer interface
 * ## Module description
 * The module defines operations on the transport layer of the business logic.
 * This includes asnStartTLS which activates TLS on a already existing TCP connection and additional operations for
 * running multiplexed connections to the UCServer (several sessions of different users on one TCP connection; creating, deleting them and user authentication).
 */

// [PrintTSROSEClass]
export class ENetUC_TransportROSE extends ROSEBase implements IInvokeHandler, IENetUC_TransportROSE {
	/**
	 * Contains the attributes that have to be filtered from logging
	 * Use logfilter property;property inside the asn1 root comments to specify this list
	 */
	public readonly logFilter: string[];

	/**
	 * The Loggers getLogData callback (used in all the log methods called in this class, add the classname to every log entry)
	 *
	 * @returns - an ILogData log data object provided additional data for all the logger calls in this class
	 */
	public getLogData(): IASN1LogData {
		return {
			className: MODULE_NAME
		};
	}

	/**
	 * Returns the operationName for an operationID
	 *
	 * @param id - the id we want to have the name for
	 * @returns - the name or undefined if not found
	 */
	public getNameForOperationID(id: OperationIDs): string | undefined {
		switch (id) {
			case OperationIDs.OPID_asnStartTLS:
				return "asnStartTLS";
			case OperationIDs.OPID_asnTransportKeepAlive:
				return "asnTransportKeepAlive";
			case OperationIDs.OPID_asnTokenVerifyV2:
				return "asnTokenVerifyV2";
			case OperationIDs.OPID_asnCheckConnection:
				return "asnCheckConnection";
			case OperationIDs.OPID_asnCreateAuthToken:
				return "asnCreateAuthToken";
			default:
				return undefined;
		}
	}

	/**
	 * Returns the operationID for an operationName
	 *
	 * @param name - the name we want to have the id for
	 * @returns - the id or undefined if not found
	 */
	public getIDForOperationName(name: string): OperationIDs | undefined {
		switch (name) {
			case "asnStartTLS":
				return OperationIDs.OPID_asnStartTLS;
			case "asnTransportKeepAlive":
				return OperationIDs.OPID_asnTransportKeepAlive;
			case "asnTokenVerifyV2":
				return OperationIDs.OPID_asnTokenVerifyV2;
			case "asnCheckConnection":
				return OperationIDs.OPID_asnCheckConnection;
			case "asnCreateAuthToken":
				return OperationIDs.OPID_asnCreateAuthToken;
			default:
				return undefined;
		}
	}

	// [PrintTSROSEConstructor]
	/**
	 * Constructs the invoke and oninvoke object targeting all the ROSE related parts.
	 *
	 * @param transport - The transport is the connection to the other side. It takes care of delivering the invoke
	 * to us as well as to send invokes and events to the other side. It also holds the logger.
	 * @param handleEvents - Set this to true if you want to receive events or false if the stub should cached them
	 * until you call dispatchEvents();
	 * @param handler - The handler takes care of handling methods that are exposed through the ASN1 file
	 * The outer ROSE envelop specifies the function that is called. The server looks for an appropriate handler
	 * and calls the handler for the operation. Inside the operation the argument is decoded. Once the handling of the
	 * operation is done the result (error) is encoded and handed back to the callee, embedded in the ROSE envelop and send
	 * back to the other side. If a certain function is not register the function call will fail with not function not implemented
	 */
	public constructor(transport: IASN1Transport, handleEvents: boolean, handler?: Partial<IENetUC_TransportROSE_Handler>) {
		super(transport, handleEvents);

		this.logFilter = [];

		if (handler)
			this.setHandler(handler);
	}

	// [PrintTSROSESetHandler]
	/**
	 * Sets the handler and registers the operations with it
	 *
	 * @param handler - The handler takes care of handling methods that are exposed through the ASN1 file
	 * The outer ROSE envelop specifies the function that is called. The server looks for an appropriate handler
	 * and calls the handler for the operation. Inside the operation the argument is decoded. Once the handling of the
	 * operation is done the result (error) is encoded and handed back to the callee, embedded in the ROSE envelop and send
	 * back to the other side. If a certain function is not register the function call will fail with not function not implemented
	 */
	public setHandler(handler: Partial<IENetUC_TransportROSE_Handler>): void {
		this.transport.registerOperation(this, handler, OperationIDs.OPID_asnStartTLS, "asnStartTLS");
		this.transport.registerOperation(this, handler, OperationIDs.OPID_asnTransportKeepAlive, "asnTransportKeepAlive");
		this.transport.registerOperation(this, handler, OperationIDs.OPID_asnTokenVerifyV2, "asnTokenVerifyV2");
		this.transport.registerOperation(this, handler, OperationIDs.OPID_asnCheckConnection, "asnCheckConnection");
		this.transport.registerOperation(this, handler, OperationIDs.OPID_asnCreateAuthToken, "asnCreateAuthToken");
		this.transport.registerModuleVersion("ENetUC_Transport", 8, 0);
	}

	// [PrintTSROSEInvokeMethods]

	// [PrintTSROSEInvokeMethod]
	/**
	 * Start TLS Handschake on existing connection
	 * Client should use this function immediately after establishing the connection.
	 * After calling this function, the UCServer switches to TLS mode and expects a regular TLS handshahe from the client.
	 *
	 * @param argument - An AsnStartTLSArgument object containing all the relevant parameters for the call
	 * @param invokeContext - Invoke related contextual data (e.g. a clientConnectionID)
	 * @returns a Promise resolving into AsnStartTLSResult, an AsnRequestError or AsnInvokeProblem object
	 */
	public async invoke_asnStartTLS(argument: ENetUC_Transport.AsnStartTLSArgument, invokeContext?: ISendInvokeContextParams): Promise<ENetUC_Transport.AsnStartTLSResult | ENetUC_Common.AsnRequestError | AsnInvokeProblem> {
		return this.handleInvoke(argument, ENetUC_Transport.AsnStartTLSResult, OperationIDs.OPID_asnStartTLS, "asnStartTLS", Converter.AsnStartTLSArgument_Converter, Converter.AsnStartTLSResult_Converter, invokeContext);
	}

	// [PrintTSROSEInvokeMethod]
	/**
	 * This function allows an external Server to check if a User token is valid
	 *
	 * @param argument - An AsnTokenVerifyV2Argument object containing all the relevant parameters for the call
	 * @param invokeContext - Invoke related contextual data (e.g. a clientConnectionID)
	 * @returns a Promise resolving into AsnTokenVerifyResult, an AsnRequestError or AsnInvokeProblem object
	 */
	public async invoke_asnTokenVerifyV2(argument: ENetUC_Transport.AsnTokenVerifyV2Argument, invokeContext?: ISendInvokeContextParams): Promise<ENetUC_Transport.AsnTokenVerifyResult | ENetUC_Common.AsnRequestError | AsnInvokeProblem> {
		return this.handleInvoke(argument, ENetUC_Transport.AsnTokenVerifyResult, OperationIDs.OPID_asnTokenVerifyV2, "asnTokenVerifyV2", Converter.AsnTokenVerifyV2Argument_Converter, Converter.AsnTokenVerifyResult_Converter, invokeContext);
	}

	// [PrintTSROSEInvokeMethod]
	/**
	 * This function allows to check if the connection to the server is functional (Mobiler Zugang überprüfung)
	 *
	 * @param argument - An AsnCheckConnectionArgument object containing all the relevant parameters for the call
	 * @param invokeContext - Invoke related contextual data (e.g. a clientConnectionID)
	 * @returns a Promise resolving into AsnCheckConnectionResult, an AsnRequestError or AsnInvokeProblem object
	 */
	public async invoke_asnCheckConnection(argument: ENetUC_Transport.AsnCheckConnectionArgument, invokeContext?: ISendInvokeContextParams): Promise<ENetUC_Transport.AsnCheckConnectionResult | ENetUC_Common.AsnRequestError | AsnInvokeProblem> {
		return this.handleInvoke(argument, ENetUC_Transport.AsnCheckConnectionResult, OperationIDs.OPID_asnCheckConnection, "asnCheckConnection", Converter.AsnCheckConnectionArgument_Converter, Converter.AsnCheckConnectionResult_Converter, invokeContext);
	}

	// [PrintTSROSEInvokeMethod]
	/**
	 * Create a auth token in the UCServer
	 *
	 * @param argument - An AsnCreateAuthTokenArgument object containing all the relevant parameters for the call
	 * @param invokeContext - Invoke related contextual data (e.g. a clientConnectionID)
	 * @returns a Promise resolving into AsnCreateAuthTokenResult, an AsnRequestError or AsnInvokeProblem object
	 */
	public async invoke_asnCreateAuthToken(argument: ENetUC_Transport.AsnCreateAuthTokenArgument, invokeContext?: ISendInvokeContextParams): Promise<ENetUC_Transport.AsnCreateAuthTokenResult | ENetUC_Common.AsnRequestError | AsnInvokeProblem> {
		return this.handleInvoke(argument, ENetUC_Transport.AsnCreateAuthTokenResult, OperationIDs.OPID_asnCreateAuthToken, "asnCreateAuthToken", Converter.AsnCreateAuthTokenArgument_Converter, Converter.AsnCreateAuthTokenResult_Converter, invokeContext);
	}

	// [PrintTSROSEInvokeMethod]
	/**
	 * @param argument - An AsnTransportKeepAliveArgument object containing all the relevant parameters for the call
	 * @param invokeContext - Invoke related contextual data (e.g. a clientConnectionID)
	 * @returns undefined or, if bSendEventSynchronous has been set true when the event was sent
	 */
	public event_asnTransportKeepAlive(argument: ENetUC_Transport.AsnTransportKeepAliveArgument, invokeContext?: ISendInvokeContextParams): undefined | boolean {
		return this.handleEvent(argument, OperationIDs.OPID_asnTransportKeepAlive, "asnTransportKeepAlive", Converter.AsnTransportKeepAliveArgument_Converter, invokeContext);
	}

	// [PrintTSROSEOnInvokeswitchCase]
	/**
	 * This is the central onInvoke method that is called whenever a method of this module is called.
	 * Based on the operationID we step into the decoding of the method argument and call the method in the handler.
	 * The result is then again encoded and send to the other side.
	 *
	 * @param invoke - The (ROSE) decoded invoke which also contains the function argument (not yet decoded). The
	 * operationID is the one that defines which function we call. In the switch case we decode the methods argument
	 * and call the metho in the handler.
	 * @param invokeContext - The invoke related contextual data (see IReceiveInvokeContext)
	 * @param handler - This object is handling the invoke after having successfully decoded the argument.
	 * it contains the methods as defined in the asn.1 files.
	 * @returns ROSEReject if the request was not handled, ROSEResult for the invoke result, ROSEError for an error or undefined if an event was called
	 */
	public async onInvoke(invoke: ROSEInvoke, invokeContext: IReceiveInvokeContext, handler: IENetUC_TransportROSE_Handler): Promise<ROSEReject | ROSEResult | ROSEError | undefined> {
		switch (invoke.operationID) {
			case OperationIDs.OPID_asnStartTLS:
				return await this.handleOnInvoke(invoke, OperationIDs.OPID_asnStartTLS, ENetUC_Transport.AsnStartTLSArgument, Converter.AsnStartTLSArgument_Converter, Converter.AsnStartTLSResult_Converter, handler, handler.onInvoke_asnStartTLS, invokeContext);
			case OperationIDs.OPID_asnTokenVerifyV2:
				return await this.handleOnInvoke(invoke, OperationIDs.OPID_asnTokenVerifyV2, ENetUC_Transport.AsnTokenVerifyV2Argument, Converter.AsnTokenVerifyV2Argument_Converter, Converter.AsnTokenVerifyResult_Converter, handler, handler.onInvoke_asnTokenVerifyV2, invokeContext);
			case OperationIDs.OPID_asnCheckConnection:
				return await this.handleOnInvoke(invoke, OperationIDs.OPID_asnCheckConnection, ENetUC_Transport.AsnCheckConnectionArgument, Converter.AsnCheckConnectionArgument_Converter, Converter.AsnCheckConnectionResult_Converter, handler, handler.onInvoke_asnCheckConnection, invokeContext);
			case OperationIDs.OPID_asnCreateAuthToken:
				return await this.handleOnInvoke(invoke, OperationIDs.OPID_asnCreateAuthToken, ENetUC_Transport.AsnCreateAuthTokenArgument, Converter.AsnCreateAuthTokenArgument_Converter, Converter.AsnCreateAuthTokenResult_Converter, handler, handler.onInvoke_asnCreateAuthToken, invokeContext);
			case OperationIDs.OPID_asnTransportKeepAlive:
				return this.onEvent(invoke, invokeContext, handler);
			default:
				// If you land here stub of client and server are incompatible...
				debugger;
				return createInvokeReject(invoke, AsnInvokeProblemEnum.unrecognisedOperation, `${invoke.operationID} ("${invoke.operationName}") is not a function of ENetUC_TransportROSE`);
		}
	}

	// [PrintTSROSEOnEventSwitchCase]
	/**
	 * This is the onEvent method that is called whenever an event is called in this module.
	 * It is called from the onInvoke in case of an event is being called.
	 * Depending on the handleEvents flag the event is either handled or cached.
	 *
	 * @param invoke - The (ROSE) decoded invoke which also contains the function argument (not yet decoded). The
	 * operationID is the one that defines which function we call. In the switch case we decode the methods argument
	 * and call the method in the handler.
	 * @param invokeContext - The invoke related contextual data (see IReceiveInvokeContext)
	 * @param handler - This object is handling the invoke after having successfully decoded the argument.
	 * it contains the methods as defined in the asn.1 files.
	 * @returns ROSEReject if the request was not handled or undefined
	 */
	private async onEvent(invoke: ROSEInvoke, invokeContext: IReceiveInvokeContext, handler: IENetUC_TransportROSE_Handler): Promise<ROSEReject | undefined> {
		// If the class says do not handle events and the override flag in the invokeContext has not been set, add the event to the que, otherwise we dispatch it
		if (!this.handleEvents && !invokeContext?.handleEvent) {
			this.transport.log(ELogSeverity.debug, "Adding event to queue", "onEvent", this, { operationName: invoke.operationName, operationID: invoke.operationID });
			this.cachedEvents.push({ invoke, invokeContext, handler });
			return;
		}

		switch (invoke.operationID) {
			case OperationIDs.OPID_asnTransportKeepAlive:
				return await this.handleOnEvent(invoke, OperationIDs.OPID_asnTransportKeepAlive, ENetUC_Transport.AsnTransportKeepAliveArgument, Converter.AsnTransportKeepAliveArgument_Converter, handler, handler.onEvent_asnTransportKeepAlive, invokeContext);
			default:
				// If you land here stub of client and server are incompatible...
				debugger;
				return createInvokeReject(invoke, AsnInvokeProblemEnum.unrecognisedOperation, `${invoke.operationID} ("${invoke.operationName}") is not a function of ENetUC_TransportROSE`);
		}
	}
}
